name: trip_repository
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.4.3

# Add regular dependencies here.
dependencies:
  equatable: ^2.0.5
  point_of_interest_service:
    path: '../point_of_interest_service'

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
